### PR TITLE
Add docker for Spark+Iceberg+Nessie+MinIO

### PR DESCRIPTION
**Pull request by ajantha-bhat**
Inspired from https://github.com/tabular-io/docker-spark-iceberg

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
> What's the benefit over https://github.com/projectnessie/nessie-demos, which can be run by everyone via a browser without the need of doing the "docker compose dance"?

- User can bring up this docker with other projects like kafka-connect.  
Example:
https://github.com/Wuerike/kafka-iceberg-streaming/blob/main/docker-compose.yaml
- Easy to use spark-shell/spark-sql for custom commands testing with Nessie catalog 


Nessie demo notebook I thought of adding to this repo also thinking it will be useful for user to understand the Nessie scenarios if they already have this docker running.

**Comment by jbonofre** [comment]
The main differences of this repo compared to nessie-demos are:
- examples will be multi-catalog, not only Nessie based
- docker images will be contributed upstream to Iceberg

I think it makes sense to cross link and do everything related to Nessie in nessie-demos.
The rest (hive/hdfs/jdbc based catalog) should be in iceland.

**Comment by snazy** [comment]
Looking forward to contributions to nessie-demos :)

**Comment by ajantha-bhat** [comment]
closing in the favour of Nessie demos

**Pull request closed without merging**
